# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

FROM nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04

# because 'docker build' cannot call GPU, so you need to run like this:
# $ docker build -t superscaler_test -f Dockerfile.test.CUDA .
# run test cases automately:
# $ docker run --runtime=nvidia --rm superscaler_test


# python version is related to tensorflow version
ARG python=3.7
ENV PYTHON_VERSION=${python}

# install the dependencies
RUN apt-get update && apt-get install --no-install-recommends --allow-downgrades -y \
    build-essential \
    git \
    wget \
    rsync \
    python${PYTHON_VERSION} \
    python${PYTHON_VERSION}-dev \
    python3-pip

RUN wget -qO- "https://cmake.org/files/v3.18/cmake-3.18.2-Linux-x86_64.tar.gz" | \
  tar --strip-components=1 -xz -C /usr/local

# set softlink of python3 and python
RUN ln -sf /usr/bin/python${PYTHON_VERSION} /usr/bin/python3 && \
    ln -sf /usr/bin/python3 /usr/bin/python

# Install python packages
COPY requirements.txt /
RUN python3 -m pip install --upgrade pip && \
    python3 -m pip install setuptools && \
    python3 -m pip install flake8 && \
    python3 -m pip install --no-cache-dir -r requirements.txt

COPY . /SuperScaler
WORKDIR /SuperScaler

CMD "/SuperScaler/tools/run_test.sh"
